# _config.yml

# 基本設定
title: "Siu - Personal Website"
description: "Fintech | Hedge Funds | Quant Research | Blockchain"
url: ""
baseurl: ""
theme: minima  # GitHub Pages 內建安全主題

# 導覽列（只留 Home）
nav:
  - title: "Home"
    url: "/"

# 作者資訊
author:
  name: "Siu"
  bio: "Fintech enthusiast. Quant + Blockchain + Hedge Funds."
  location: "Hong Kong"
  email: "Kingstonsiu20040801@gmail.com"
  github: "siiiiiiiiii"

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 預設頁面設定
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# 讓 Jekyll 部署時包含 assets 裡的 PDF 檔
include:
  - assets/Report_Investment.pdf
