# --- 基本設定 ---
title: "Siu - Personal Website"
description: "Fintech | Hedge Funds | Quant Research | Blockchain"
url: ""
baseurl: ""

theme: minima  # GitHub Pages 內建安全主題

# --- 允許 Jekyll 部署 PDF 檔案 (非常重要) ---
include:
  - "Report_Investment.pdf"

# --- Plugins (GitHub Pages 預設支持 jekyll-feed, jekyll-sitemap) ---
plugins:
  - jekyll-feed
  - jekyll-sitemap

# --- 預設頁面設定 (為所有 Pages 指定 Layout) ---
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
