# 基本設定
title: "Siu - Personal Website"
description: "Fintech | Hedge Funds | Quant Research | Blockchain"
url: ""             # 必須為空
baseurl: ""         # 必須為空

# 主題：使用 GitHub Pages 內建好看的 cayman 主題
theme: jekyll-theme-cayman

# 導覽列（只保留 Home 和 Projects）
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: /portfolio/

# 作者資訊（會顯示在首頁最上方）
author:
  name: "Siu"
  bio: "Fintech enthusiast. Quant + Blockchain + Hedge Funds."
  location: "Hong Kong"
  email: "Kingstonsiu20040801@gmail.com"
  github: "siiiiiiiiii"

# 自訂 Collection 用來顯示 Project
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# 預設版型設定
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: portfolio
    values:
      layout: default

# 插件（Pages 支援）
plugins:
  - jekyll-feed
  - jekyll-sitemap
